/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 *
 * @author XaviO_o
 */
public class Citas extends javax.swing.JFrame {

    /**
     * Creates new form Citas
     */
    FondoPanel f = new FondoPanel();
    public Citas() {
        f.ubi = "/imagenes/fondogrande.png";
        this.setContentPane(f);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    class FondoPanel extends JPanel {

        Image img;        
        String ubi = "";
        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource(ubi)).getImage();
            
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    
        public void setUbi(String ubi) {
            this.ubi = ubi;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel f = new FondoPanel();
        f.ubi = "/imagenes/cabCitas.png";
        jPanel1 = f;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscarCita = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tipoMascota = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        correoCitas = new javax.swing.JLabel();
        nombreCitas = new javax.swing.JLabel();
        cedulaCitas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dateCitas = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        nombreMascCitas = new javax.swing.JTextField();
        veterinarioCitas = new javax.swing.JComboBox<>();
        addClienteCita = new javax.swing.JButton();
        agendarCita = new javax.swing.JButton();
        horaCitas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(870, 620));
        setMinimumSize(new java.awt.Dimension(870, 620));
        setPreferredSize(new java.awt.Dimension(870, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 91));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 119, 144));
        jLabel1.setText("REGISTRO DE LAS CITAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 340, 30));

        buscarCita.setBackground(new java.awt.Color(255, 255, 253));
        buscarCita.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        buscarCita.setForeground(new java.awt.Color(28, 119, 144));
        buscarCita.setText("Buscar");
        buscarCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        buscarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarCitaMouseExited(evt);
            }
        });
        jPanel2.add(buscarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 160, 40));

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel11.setText("Fecha");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 120, 20));

        tipoMascota.setBackground(new java.awt.Color(204, 204, 204));
        tipoMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de mascota" }));
        tipoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(tipoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 350, 40));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel4.setText("Correo Electronico:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, 20));

        correoCitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(correoCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 350, 40));

        nombreCitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(nombreCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 350, 40));

        cedulaCitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(cedulaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 350, 40));

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel13.setText("Cliente C.I:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 20));

        dateCitas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(dateCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 180, 40));

        jLabel14.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel14.setText("Nombre de la Mascota:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 20));

        nombreMascCitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(nombreMascCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 350, 40));

        veterinarioCitas.setBackground(new java.awt.Color(204, 204, 204));
        veterinarioCitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione al Medico Veterinario" }));
        veterinarioCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinarioCitasActionPerformed(evt);
            }
        });
        jPanel2.add(veterinarioCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 350, 40));

        addClienteCita.setBackground(new java.awt.Color(255, 255, 253));
        addClienteCita.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        addClienteCita.setForeground(new java.awt.Color(28, 119, 144));
        addClienteCita.setText("Nuevo Cliente");
        addClienteCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        addClienteCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addClienteCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addClienteCitaMouseExited(evt);
            }
        });
        jPanel2.add(addClienteCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, 40));

        agendarCita.setBackground(new java.awt.Color(255, 255, 253));
        agendarCita.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        agendarCita.setForeground(new java.awt.Color(28, 119, 144));
        agendarCita.setText("Agendar");
        agendarCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        agendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agendarCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agendarCitaMouseExited(evt);
            }
        });
        jPanel2.add(agendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, 50));

        horaCitas.setBackground(new java.awt.Color(204, 204, 204));
        horaCitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Hora", "08:00", "09:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00", "17:00" }));
        jPanel2.add(horaCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 150, 40));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 60, 20));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel7.setText("Hora:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 40, 20));

        jLabel12.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel12.setText("Veterinario:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 790, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarCitaMouseEntered
        buscarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_buscarCitaMouseEntered

    private void buscarCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarCitaMouseExited
        buscarCita.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_buscarCitaMouseExited

    private void tipoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMascotaActionPerformed

    private void veterinarioCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarioCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veterinarioCitasActionPerformed

    private void addClienteCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClienteCitaMouseEntered
        buscarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_addClienteCitaMouseEntered

    private void addClienteCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClienteCitaMouseExited
        buscarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_addClienteCitaMouseExited

    private void agendarCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarCitaMouseEntered
        buscarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_agendarCitaMouseEntered

    private void agendarCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarCitaMouseExited
        buscarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_agendarCitaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citas().setVisible(true);
            }
        });
    }
    
    public void listenerBuscarClienteCita(ActionListener l){
        buscarCita.addActionListener(l);
    }
    
     public void listeneraddClienteCita(ActionListener l){
        addClienteCita.addActionListener(l);
    }
    
    public void listenerAgendarCita(ActionListener l){
        agendarCita.addActionListener(l);
    }

    public JTextField getCedulaCitas() {
        return cedulaCitas;
    }

    public void setCedulaCitas(JTextField cedulaCitas) {
        this.cedulaCitas = cedulaCitas;
    }

    public JLabel getCorreoCitas() {
        return correoCitas;
    }

    public void setCorreoCitas(JLabel correoCitas) {
        this.correoCitas = correoCitas;
    }

    public JDateChooser getDateCitas() {
        return dateCitas;
    }

    public void setDateCitas(JDateChooser dateCitas) {
        this.dateCitas = dateCitas;
    }

    public JComboBox<String> getHoraCitas() {
        return horaCitas;
    }

    public void setHoraCitas(JComboBox<String> horaCitas) {
        this.horaCitas = horaCitas;
    }

    public JLabel getNombreCitas() {
        return nombreCitas;
    }

    public void setNombreCitas(JLabel nombreCitas) {
        this.nombreCitas = nombreCitas;
    }

    public JTextField getNombreMascCitas() {
        return nombreMascCitas;
    }

    public void setNombreMascCitas(JTextField nombreMascCitas) {
        this.nombreMascCitas = nombreMascCitas;
    }

    public JComboBox<String> getTipoMascota() {
        return tipoMascota;
    }

    public void setTipoMascota(JComboBox<String> tipoMascota) {
        this.tipoMascota = tipoMascota;
    }

    public JComboBox<String> getVeterinarioCitas() {
        return veterinarioCitas;
    }

    public void setVeterinarioCitas(JComboBox<String> veterinarioCitas) {
        this.veterinarioCitas = veterinarioCitas;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClienteCita;
    private javax.swing.JButton agendarCita;
    private javax.swing.JButton buscarCita;
    private javax.swing.JTextField cedulaCitas;
    private javax.swing.JLabel correoCitas;
    private com.toedter.calendar.JDateChooser dateCitas;
    private javax.swing.JComboBox<String> horaCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreCitas;
    private javax.swing.JTextField nombreMascCitas;
    private javax.swing.JComboBox<String> tipoMascota;
    private javax.swing.JComboBox<String> veterinarioCitas;
    // End of variables declaration//GEN-END:variables
}
