/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.TableModel;

/**
 *
 * @author XaviO_o
 */
public class Servicios extends javax.swing.JFrame {

    FondoPanel f = new FondoPanel();
    public Servicios() {
        
        f.ubi = "/imagenes/fondogrande.png";
        this.setContentPane(f);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel f = new FondoPanel();
        f.ubi = "/imagenes/controlServicios.png";
        jPanel1 = f;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviciosTable = new javax.swing.JTable();
        eliminarServicio = new javax.swing.JButton();
        crearActServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1215, 780));
        setSize(new java.awt.Dimension(1215, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 126));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 119, 144));
        jLabel1.setText("CONTROL DE LOS SERVICIOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, 40));

        serviciosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(serviciosTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1100, -1));

        eliminarServicio.setBackground(new java.awt.Color(255, 255, 253));
        eliminarServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        eliminarServicio.setForeground(new java.awt.Color(28, 119, 144));
        eliminarServicio.setText("Eliminar un Servicio");
        eliminarServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        eliminarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarServicioMouseExited(evt);
            }
        });
        jPanel2.add(eliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 340, 50));

        crearActServicio.setBackground(new java.awt.Color(255, 255, 253));
        crearActServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        crearActServicio.setForeground(new java.awt.Color(28, 119, 144));
        crearActServicio.setText("Crear o Actualizar Servicios");
        crearActServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        crearActServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearActServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearActServicioMouseExited(evt);
            }
        });
        jPanel2.add(crearActServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 340, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1160, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class FondoPanel extends JPanel {

        Image img;        
        String ubi = "";
        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource(ubi)).getImage();
            
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    
        public void setUbi(String ubi) {
            this.ubi = ubi;
        }
    }
    private void eliminarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarServicioMouseEntered
        eliminarServicio.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_eliminarServicioMouseEntered

    private void eliminarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarServicioMouseExited
        eliminarServicio.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_eliminarServicioMouseExited

    private void crearActServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearActServicioMouseEntered
        crearActServicio.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_crearActServicioMouseEntered

    private void crearActServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearActServicioMouseExited
        crearActServicio.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_crearActServicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }
    
    public void listenerCrearActualizarServicio(ActionListener l){
        crearActServicio.addActionListener(l);
    }
    
    public void listenerEliminarServicio(ActionListener l){
        eliminarServicio.addActionListener(l);
    }
    
    public void setModelTableServicios(TableModel m){
        serviciosTable.setModel(m);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearActServicio;
    private javax.swing.JButton eliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable serviciosTable;
    // End of variables declaration//GEN-END:variables
}
