/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author XaviO_o
 */
public class VistaMostrarCitas extends javax.swing.JFrame {

    FondoPanel f = new FondoPanel();
    public VistaMostrarCitas() {
        
        f.ubi = "/imagenes/fondogrande.png";
        this.setContentPane(f);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel f = new FondoPanel();
        f.ubi = "/imagenes/cabeceraCitas.png";
        jPanel1 = f;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        citasTable = new javax.swing.JTable();
        CrearCita = new javax.swing.JButton();
        cancelarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1215, 780));
        setSize(new java.awt.Dimension(1215, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 126));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 119, 144));
        jLabel1.setText("CONTROL DE LAS CITAS AGENDAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, 40));

        citasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(citasTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1100, -1));

        CrearCita.setBackground(new java.awt.Color(255, 255, 253));
        CrearCita.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        CrearCita.setForeground(new java.awt.Color(28, 119, 144));
        CrearCita.setText("Crear Cita");
        CrearCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        CrearCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearCitaMouseExited(evt);
            }
        });
        jPanel2.add(CrearCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 340, 50));

        cancelarCita.setBackground(new java.awt.Color(255, 255, 253));
        cancelarCita.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        cancelarCita.setForeground(new java.awt.Color(28, 119, 144));
        cancelarCita.setText("Cancelar Cita");
        cancelarCita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        cancelarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarCitaMouseExited(evt);
            }
        });
        jPanel2.add(cancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 340, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1160, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class FondoPanel extends JPanel {

        Image img;        
        String ubi = "";
        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource(ubi)).getImage();
            
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    
        public void setUbi(String ubi) {
            this.ubi = ubi;
        }
    }
    private void CrearCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCitaMouseEntered
        CrearCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_CrearCitaMouseEntered

    private void CrearCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCitaMouseExited
        CrearCita.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_CrearCitaMouseExited

    private void cancelarCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarCitaMouseEntered
        cancelarCita.setBackground(new Color(180,245,245));
    }//GEN-LAST:event_cancelarCitaMouseEntered

    private void cancelarCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarCitaMouseExited
        cancelarCita.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_cancelarCitaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMostrarCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMostrarCitas().setVisible(true);
            }
        });
    }
    
    public void listenerCrearCita(ActionListener l){
        CrearCita.addActionListener(l);
    }
    
    public void listenerCancelarCita(ActionListener l){
        cancelarCita.addActionListener(l);
    }
    
    
    public void setModelTableServicios(TableModel m){
        citasTable.setModel(m);
    }

    public JButton getCrearCita() {
        return CrearCita;
    }

    public JButton getCancelarCita() {
        return cancelarCita;
    }

    public JTable getCitasTable() {
        return citasTable;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearCita;
    private javax.swing.JButton cancelarCita;
    private javax.swing.JTable citasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
