/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author XaviO_o
 */
public class VistaCrearServicios extends javax.swing.JFrame {

    /**
     * Creates new form VistaCrearServicios
     */
    FondoPanel fondo = new FondoPanel();
    public VistaCrearServicios() {
        fondo.ubi="/imagenes/fondogrande.png";
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public void listenerBuscarServicio(ActionListener l){
        buscarServicio.addActionListener(l);
    }
    
    public void listenerActualizarServicio(ActionListener l){
        actualizarServicio.addActionListener(l);
    }
    
    public void listenerlimpiarServicio(ActionListener l){
        limpiarServicio.addActionListener(l);
    }
    
    
    public void listenerCrearServicio(ActionListener l){
        crearServicio.addActionListener(l);
    }

    public JButton getActualizarServicio() {
        return actualizarServicio;
    }

    public JButton getBuscarServicio() {
        return buscarServicio;
    }

    public JButton getCrearServicio() {
        return crearServicio;
    }

    
    public JTextField getCodigoServicio() {
        return codigoServicio;
    }

    public JTextArea getDescripcionServicio() {
        return descripcionServicio;
    }

    public JComboBox<String> getIvaBoxServicio() {
        return ivaBoxServicio;
    }

    public JTextField getNombreServicio() {
        return nombreServicio;
    }

    public JTextField getPrecioServicio() {
        return precioServicio;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel f = new FondoPanel();
        f.ubi = "/imagenes/añadirServiciocab.png";
        jPanel1 = f;
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreServicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precioServicio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        limpiarServicio = new javax.swing.JButton();
        buscarServicio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ivaBoxServicio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionServicio = new javax.swing.JTextArea();
        codigoServicio = new javax.swing.JTextField();
        crearServicio = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        actualizarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(797, 490));
        setMinimumSize(new java.awt.Dimension(797, 490));
        setPreferredSize(new java.awt.Dimension(797, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 83));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 119, 144));
        jLabel1.setText("Añadir Servicios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 70, 20));

        nombreServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(nombreServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 400, 40));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel3.setText("Tiene IVA:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 70, 20));

        precioServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(precioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 40));

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel11.setText("Codigo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 50, 20));

        limpiarServicio.setBackground(new java.awt.Color(255, 255, 253));
        limpiarServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        limpiarServicio.setForeground(new java.awt.Color(28, 119, 144));
        limpiarServicio.setText("Limpiar Todo");
        limpiarServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        limpiarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarServicioMouseExited(evt);
            }
        });
        limpiarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarServicioActionPerformed(evt);
            }
        });
        jPanel2.add(limpiarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 260, 40));

        buscarServicio.setBackground(new java.awt.Color(255, 255, 255));
        buscarServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        buscarServicio.setForeground(new java.awt.Color(28, 119, 144));
        buscarServicio.setText("Buscar");
        buscarServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        buscarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarServicioMouseExited(evt);
            }
        });
        jPanel2.add(buscarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 40));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 20));

        ivaBoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "SI", "NO" }));
        jPanel2.add(ivaBoxServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 180, 40));

        descripcionServicio.setColumns(20);
        descripcionServicio.setRows(5);
        jScrollPane1.setViewportView(descripcionServicio);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 260, 120));

        codigoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.add(codigoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, 40));

        crearServicio.setBackground(new java.awt.Color(255, 255, 255));
        crearServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        crearServicio.setForeground(new java.awt.Color(28, 119, 144));
        crearServicio.setText("Crear");
        crearServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        crearServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearServicioMouseExited(evt);
            }
        });
        jPanel2.add(crearServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 40));

        jLabel12.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel12.setText("Nombre");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, 20));

        actualizarServicio.setBackground(new java.awt.Color(255, 255, 253));
        actualizarServicio.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        actualizarServicio.setForeground(new java.awt.Color(28, 119, 144));
        actualizarServicio.setText("Actualizar");
        actualizarServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 245, 245), 2, true));
        actualizarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizarServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizarServicioMouseExited(evt);
            }
        });
        actualizarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarServicioActionPerformed(evt);
            }
        });
        jPanel2.add(actualizarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 180, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 740, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarServicioMouseEntered
        limpiarServicio.setBackground(new Color(180, 245, 245));
    }//GEN-LAST:event_limpiarServicioMouseEntered

    private void limpiarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarServicioMouseExited
        limpiarServicio.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_limpiarServicioMouseExited

    private void limpiarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarServicioActionPerformed

    private void buscarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarServicioMouseEntered
        buscarServicio.setBackground(new Color(180, 245, 245));
    }//GEN-LAST:event_buscarServicioMouseEntered

    private void buscarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarServicioMouseExited
        buscarServicio.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_buscarServicioMouseExited

    private void crearServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearServicioMouseEntered
        crearServicio.setBackground(new Color(180, 245, 245));
    }//GEN-LAST:event_crearServicioMouseEntered

    private void crearServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearServicioMouseExited
        crearServicio.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_crearServicioMouseExited

    private void actualizarServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarServicioMouseEntered
        actualizarServicio.setBackground(new Color(180, 245, 245));
    }//GEN-LAST:event_actualizarServicioMouseEntered

    private void actualizarServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarServicioMouseExited
        actualizarServicio.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_actualizarServicioMouseExited

    private void actualizarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarServicioActionPerformed
    class FondoPanel extends JPanel {

        Image img;
        String ubi = "";

        @Override
        public void paint(Graphics g) {
            img = new ImageIcon(getClass().getResource(ubi)).getImage();

            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }

        public void setUbi(String ubi) {
            this.ubi = ubi;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarServicio;
    private javax.swing.JButton buscarServicio;
    private javax.swing.JTextField codigoServicio;
    private javax.swing.JButton crearServicio;
    private javax.swing.JTextArea descripcionServicio;
    private javax.swing.JComboBox<String> ivaBoxServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarServicio;
    private javax.swing.JTextField nombreServicio;
    private javax.swing.JTextField precioServicio;
    // End of variables declaration//GEN-END:variables
}
